version: '2'

services:
    server:
        build: ./src
        command: bash -c "taskset --cpu-list 3 /src/server 0 128"
        volumes:
            - ./src:/src
        ports:
            - "12345:12345"
        tty: true
