# Generated by Django 3.0.2 on 2020-02-05 20:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200205_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 20, 45, 21, 4694, tzinfo=utc)),
        ),
    ]
