# Generated by Django 3.0.2 on 2020-02-05 18:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('sharer', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('destination', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField(default=datetime.datetime(2020, 2, 5, 18, 1, 28, 971297, tzinfo=utc))),
                ('total_pass', models.IntegerField(default=1)),
                ('sharing', models.BooleanField(default=False)),
                ('status', models.CharField(default='Open', max_length=100)),
                ('vehicle_type', models.CharField(blank=True, choices=[('suv', 'SUV'), ('track', 'TRACK'), ('sedan', 'SEDAN')], default='SUV', max_length=100)),
                ('other_request', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sharer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sharer', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_driver', models.BooleanField(default=False)),
                ('plate_number', models.CharField(max_length=100)),
                ('max_pass', models.PositiveIntegerField(default=5)),
                ('vehicle_type', models.CharField(blank=True, choices=[('suv', 'SUV'), ('track', 'TRACK'), ('sedan', 'SEDAN')], default='SUV', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
