# Generated by Django 3.0.2 on 2020-02-05 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 18, 56, 41, 896289, tzinfo=utc)),
        ),
    ]
