# Generated by Django 2.2.9 on 2020-02-05 20:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200205_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 20, 17, 16, 720, tzinfo=utc)),
        ),
    ]
