# Generated by Django 2.2.9 on 2020-02-05 20:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200205_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 20, 21, 34, 30568, tzinfo=utc)),
        ),
    ]
