# Generated by Django 2.2.9 on 2020-02-06 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200206_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 6, 14, 33, 9, 944807, tzinfo=utc)),
        ),
    ]
