# Generated by Django 3.0.5 on 2020-04-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.IntegerField()),
                ('dst_x', models.IntegerField()),
                ('dst_y', models.IntegerField()),
                ('cur_x', models.IntegerField()),
                ('cur_y', models.IntegerField()),
                ('status', models.CharField(default='created', max_length=200)),
                ('truck_id', models.IntegerField()),
            ],
        ),
    ]
