# Generated by Django 3.0.5 on 2020-04-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_auto_20200421_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='cur_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='cur_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
