# Generated by Django 3.0.5 on 2020-04-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_auto_20200421_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='owner',
            field=models.CharField(default='', max_length=200),
        ),
    ]
