# Generated by Django 3.0.2 on 2020-01-29 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dst', models.CharField(max_length=200, verbose_name='Destination')),
                ('arrivial_time', models.DateTimeField(help_text='Format: 2020-01-01 12:00', null=True)),
                ('order_pass_num', models.IntegerField(default=0, null=True)),
                ('is_share', models.BooleanField(default=False)),
                ('owner_pass_num', models.IntegerField(default=0, null=True)),
                ('special_request', models.TextField(blank=True, default='null', help_text='Do you have any other requests', max_length=200, null=True)),
                ('special_vehicle_type', models.CharField(blank=True, default='null', help_text='Car type', max_length=200, null=True)),
                ('license_plate_number', models.CharField(blank=True, default='xxx', help_text="user's license_plate_number", max_length=50, null=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('confirm', 'confirm'), ('complete', 'complete')], default='open', max_length=20)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sharer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_pass_num', models.IntegerField(default=0, null=True)),
                ('early_time', models.DateTimeField(help_text='Format: 2020-01-01 12:00', verbose_name='Early acceptable arrive date')),
                ('last_time', models.DateTimeField(help_text='Format: 2020-01-01 12:00', verbose_name='Latest acceptable arrive date')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RideApp.Order')),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_driver', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(blank=True, help_text="user's vehicle type", max_length=50, null=True)),
                ('special_request', models.CharField(blank=True, help_text="user's special reequest", max_length=50, null=True)),
                ('max_car_pass', models.IntegerField(blank=True, help_text="car's max passenger", null=True)),
                ('license_plate_number', models.CharField(blank=True, help_text="user's license_plate_number", max_length=50, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
